### ISSUE TITLE
[TODO]: Clean up strings/translations

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/plugwise_usb-beta#4]
### Todo

[custom_components/plugwise_usb/strings.json](https://github.com/plugwise/plugwise_usb-beta/pull/1/files/2cbfcbc723f4d1a16dd80717b7f28ea72a06c8d1#diff-414a978a05ad35d220681297886fbe54fa7f09243ff385bb131db1f221d45899)

- [ ] All translations are related to Anna/Adam/P1, these can all be removed.

- [ ] Also, other stuff can be removed because the Config Flow is much simpler now.

- [ ] And, don't forget to update the translation-files
