### ISSUE TITLE
[FEATURE]: Core compatibility

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/plugwise_usb-beta#9]
### Describe the solution you are looking for

As discovered by both @CoMPaTech and @bouwew `mypy` throws a spanner in the works when upstreaming to Core. As such `mypy` should be part of our routine when updating/adding code to this repository.

### Is your feature request related to a problem? (optional)

n/a

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

Smile: Adam (including Lisa, Tom, Floor)

### What firmware version is your Plugwise product at?

core-dev

### Your setup

n/a

### Additional context

Todolist

- [x] Introduce ```script/run-in-env.sh mypy homeassistant/components/plugwise/*.py``` into core-testing - branch `mypy` plugwise/plugwise-beta#267 
- [x] ```homeassistant/components/plugwise/coordinator.py:30: error: Argument "update_interval" to "__init__" of "DataUpdateCoordinator" has incompatible type "float"; expected "Optional[timedelta]"  [arg-type]``` - branch `mypy_coordinator` plugwise/plugwise-beta#266 
- [x] ```homeassistant/components/plugwise/config_flow.py:86: error: Incompatible return value type (got "Tuple[Dict[str, str], None]", expected "Dict[str, str]")  [return-value]```
- [x] ```homeassistant/components/plugwise/config_flow.py:101: error: Incompatible return value type (got "Tuple[Dict[str, str], Any]", expected "Dict[str, str]")  [return-value]```
- [ ] ```homeassistant/components/plugwise/usb.py:202: error: "PlugwiseEntityDescription" has no attribute "should_poll"  [attr-defined]```
- [x] ```homeassistant/components/plugwise/gateway.py:89: error: Argument 3 to "PlugwiseDataUpdateCoordinator" has incompatible type "timedelta"; expected "float"  [arg-type]``` plugwise/plugwise-beta#266 
- [x] ```homeassistant/components/plugwise/entity.py:18: error: Type argument "PlugwiseData" of "CoordinatorEntity" must be a subtype of "DataUpdateCoordinator[Any]"  [type-var]```
- [x] ```homeassistant/components/plugwise/entity.py:21: error: Incompatible types in assignment (expression has type "PlugwiseDataUpdateCoordinator", base class "CoordinatorEntity" defined the type as "PlugwiseData")  [assignment]```
- [x] ```homeassistant/components/plugwise/entity.py:29: error: Argument 1 to "__init__" of "CoordinatorEntity" has incompatible type "PlugwiseDataUpdateCoordinator"; expected "PlugwiseData"  [arg-type]```
- [x] ```homeassistant/components/plugwise/sensor.py:111: error: Invalid index type "str" for "str"; expected type "Union[SupportsIndex, slice]"  [index]```
- [ ] ```homeassistant/components/plugwise/sensor.py:159: error: "SensorEntityDescription" has no attribute "state_request_method"  [attr-defined]```
- [x] ```homeassistant/components/plugwise/select.py:105: error: "SelectEntityDescription" has no attribute "current_option"  [attr-defined]```
- [x] ```homeassistant/components/plugwise/select.py:110: error: "SelectEntityDescription" has no attribute "options"  [attr-defined]```
- [x] ```homeassistant/components/plugwise/select.py:115: error: "SelectEntityDescription" has no attribute "command"  [attr-defined]```
- [x] ```homeassistant/components/plugwise/number.py:96: error: Argument 1 to "async_send_api_call" of "PlugwiseEntity" has incompatible type "float"; expected "str"  [arg-type]```
- [x] ```homeassistant/components/plugwise/number.py:96: error: "NumberEntityDescription" has no attribute "command"  [attr-defined]```
- [ ] ```homeassistant/components/plugwise/binary_sensor.py:208: error: "BinarySensorEntityDescription" has no attribute "state_request_method"  [attr-defined]```
- [ ] ```homeassistant/components/plugwise/switch.py:152: error: "SwitchEntityDescription" has no attribute "state_request_method"  [attr-defined]```
- [x] ```homeassistant/components/plugwise/climate.py:112: error: Incompatible return value type (got "Optional[Any]", expected "str")  [return-value]```

**Comment by CoMPaTech** [comment]
Creating new more generic issue referring to this issue.
